/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Entidades.Entrada;
import Models.Entidades.Produto;
import Models.Entidades.Saida;
import Models.Interfaces.Movimentacao;
import Services.ServicesEntidades.*;
import Services.Utils.DateMaskFilter;
import Services.Utils.UtilsDateFormat;

import javax.swing.*;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.*;
import java.time.format.DateTimeParseException;

import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Usuario
 */
public class InventoryGUI extends JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    private ProdutoService produtoService;
    private EntradaService entradaService;
    private SaidaService saidaService;
    private MovimentoService movimentoService;
    private UtilsDateFormat utilsDateFormat;

    public InventoryGUI() {
        initComponents();

        ((AbstractDocument) txDataEntrada.getDocument()).setDocumentFilter(new DateMaskFilter());
        ((AbstractDocument) txDataFim.getDocument()).setDocumentFilter(new DateMaskFilter());
        ((AbstractDocument) txDataSaida.getDocument()).setDocumentFilter(new DateMaskFilter());

        produtoService = new ProdutoService();
        entradaService = new EntradaService();
        saidaService = new SaidaService();
        movimentoService = new MovimentoService(entradaService,saidaService);

        // Atualiza as tabelas
        atualizarTabelaProdutos();
        atualizarTabelaEntradas();
        atualizarTabelaSaidas();
        atualizarTabelaMovimentos();
    }

    private void atualizarTabelaEntradas() {
        DefaultTableModel model = (DefaultTableModel) tabAdicao.getModel();
        model.setRowCount(0);

        for (Entrada e : entradaService.listarTodos()) {
            model.addRow(new Object[]{
                    UtilsDateFormat.format(e.getData()), // <-- formatando
                    e.getSku(),
                    e.getQuantidade(),
                    e.getValorUnitario()
            });
        }
    }

    private void atualizarTabelaProdutos() {
        DefaultTableModel model = (DefaultTableModel) tabProduto.getModel();
        model.setRowCount(0);

        for (Produto p : produtoService.listarTodos()) {
            model.addRow(new Object[]{
                p.getSku(), p.getNome(), p.getCategoria(),
                p.getPrecoUnitario(), p.getQuantidade()
            });
        }
    }

    private void atualizarTabelaSaidas() {
        DefaultTableModel model = (DefaultTableModel) tabRemocao.getModel();
        model.setRowCount(0);

        for (Saida s : saidaService.listarTodos()) {
            model.addRow(new Object[]{
                    UtilsDateFormat.format(s.getData()), s.getSku(), s.getQuantidade()
            });
        }
    }

    private void atualizarTabelaMovimentos() {
        DefaultTableModel model = (DefaultTableModel) tabMovimentos.getModel();
        model.setRowCount(0);


        for (Movimentacao m : movimentoService.listarMovimentosOrdenados()) {
            model.addRow(new Object[]{
                    m.getData(),
                    m.isEntrada() ? "ENTRADA" : "SAÍDA",
                    m.getSku(),
                    m.getQuantidade(),
                    m.getValorUnitario()
            });
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        tab = new JTabbedPane();
        jpProduto = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        txSKU = new JTextField();
        jLabel3 = new JLabel();
        txNome = new JTextField();
        jLabel4 = new JLabel();
        jcCategoria = new JComboBox<>();
        jLabel5 = new JLabel();
        txPreco = new JTextField();
        jcTabela = new JScrollPane();
        tabProduto = new JTable();
        jbNovo = new JButton();
        jbExcluir = new JButton();
        jbSalvar = new JButton();
        jpEntrada = new JPanel();
        jLabel6 = new JLabel();
        txSkuEntrada = new JTextField();
        jLabel7 = new JLabel();
        txDataEntrada = new JTextField();
        jLabel8 = new JLabel();
        txQtdEntrada = new JTextField();
        jLabel9 = new JLabel();
        txValorEntrada = new JTextField();
        jScrollPane2 = new JScrollPane();
        tabAdicao = new JTable();
        jbRegEntrada = new JButton();
        jLabel17 = new JLabel();
        jpSaida = new JPanel();
        jLabel10 = new JLabel();
        txSkuSaida = new JTextField();
        jLabel11 = new JLabel();
        txDataSaida = new JTextField();
        jLabel12 = new JLabel();
        txQtdSaida = new JTextField();
        jScrollPane3 = new JScrollPane();
        tabRemocao = new JTable();
        jbRegSaida = new JButton();
        jLabel18 = new JLabel();
        jpSaldo = new JPanel();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        txDataInicial = new JTextField();
        txDataFim = new JTextField();
        jLabel15 = new JLabel();
        txSaldoTotal = new JTextField();
        jbChecarSaldo = new JButton();
        jLabel16 = new JLabel();
        jpMovimentos = new JPanel();
        jScrollPane4 = new JScrollPane();
        tabMovimentos = new JTable();
        jPanel2 = new JPanel();
        bntProduto = new JButton();
        btnExit = new JButton();
        btnEntry = new JButton();
        btnSaldo = new JButton();
        btnLista = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        tab.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        tab.setPreferredSize(new Dimension(450, 772));

        jpProduto.setBorder(BorderFactory.createTitledBorder(""));
        jpProduto.setToolTipText("");

        jLabel1.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");
        jLabel1.setBorder(BorderFactory.createTitledBorder(""));

        jLabel2.setText("SKU");


        txSKU.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txSKUActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        jLabel4.setText("Categoria");

        jcCategoria.setModel(new DefaultComboBoxModel<>(new String[] { "Hardware", "Perifericos", "Acessorios", "Outros" }));

        jLabel5.setText("Preço Unitario Padrão");

        txPreco.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txPrecoActionPerformed(evt);
            }
        });

        tabProduto.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SKU", "Nome", "Categoria", "Valor Unitario", "Estoque"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, Integer.class, Double.class, Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jcTabela.setViewportView(tabProduto);

        jbNovo.setText("Novo");

        jbExcluir.setText("Excluir");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        GroupLayout jpProdutoLayout = new GroupLayout(jpProduto);
        jpProduto.setLayout(jpProdutoLayout);
        jpProdutoLayout.setHorizontalGroup(
            jpProdutoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jpProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpProdutoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jbExcluir)
                    .addComponent(jbNovo))
                .addGap(21, 21, 21))
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addGroup(jpProdutoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jpProdutoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jcTabela, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpProdutoLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(txSKU)
                                .addComponent(jLabel3)
                                .addComponent(txNome)
                                .addComponent(jcCategoria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(txPreco, GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))))
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jbSalvar)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpProdutoLayout.setVerticalGroup(
            jpProdutoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpProdutoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jbNovo))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExcluir)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txSKU, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcCategoria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txPreco, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSalvar)
                .addGap(15, 15, 15)
                .addComponent(jcTabela, GroupLayout.PREFERRED_SIZE, 222, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        tab.addTab("", jpProduto);

        jLabel6.setText("SKU");

        jLabel7.setText("Data");

        txDataEntrada.setToolTipText("");

        jLabel8.setText("Produtos a Adicionar");

        jLabel9.setText("Valor Unitario");

        tabAdicao.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "SKU do produto", "Quantidade adicionada"
            }
        ) {
            Class[] types = new Class [] {
                Object.class, Integer.class, Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabAdicao);

        jbRegEntrada.setText("Registrar");
        jbRegEntrada.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbRegEntradaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Registrar Entrada");

        GroupLayout jpEntradaLayout = new GroupLayout(jpEntrada);
        jpEntrada.setLayout(jpEntradaLayout);
        jpEntradaLayout.setHorizontalGroup(
            jpEntradaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpEntradaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jpEntradaLayout.createSequentialGroup()
                .addGroup(jpEntradaLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEntradaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txValorEntrada, GroupLayout.PREFERRED_SIZE, 199, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.LEADING, jpEntradaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jpEntradaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jpEntradaLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addGroup(jpEntradaLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(txSkuEntrada)
                                    .addComponent(txDataEntrada, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txQtdEntrada, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRegEntrada)
                .addGap(65, 65, 65))
        );
        jpEntradaLayout.setVerticalGroup(
            jpEntradaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEntradaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jbRegEntrada))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txSkuEntrada, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txDataEntrada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txQtdEntrada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txValorEntrada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 265, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        tab.addTab("", jpEntrada);

        jLabel10.setText("SKU");

        jLabel11.setText("Data de Saida");

        jLabel12.setText("Quantidade a ser Removida");

        txQtdSaida.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txQtdSaidaActionPerformed(evt);
            }
        });

        tabRemocao.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "SKU do produto", "Quantidade removida"
            }
        ) {
            Class[] types = new Class [] {
                Object.class, Integer.class, Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabRemocao);

        jbRegSaida.setText("Registrar");
        jbRegSaida.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbRegSaidaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Registar Saida");

        GroupLayout jpSaidaLayout = new GroupLayout(jpSaida);
        jpSaida.setLayout(jpSaidaLayout);
        jpSaidaLayout.setHorizontalGroup(
            jpSaidaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpSaidaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpSaidaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jpSaidaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpSaidaLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jpSaidaLayout.createSequentialGroup()
                        .addGroup(jpSaidaLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(txDataSaida, GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(txSkuSaida)
                            .addComponent(jLabel11)
                            .addComponent(txQtdSaida))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbRegSaida)
                        .addGap(36, 36, 36))))
        );
        jpSaidaLayout.setVerticalGroup(
            jpSaidaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpSaidaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel18)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSaidaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jbRegSaida))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txSkuSaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txDataSaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txQtdSaida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 265, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        tab.addTab("", jpSaida);

        jLabel13.setText("Data - começo:");

        jLabel14.setText("Data - Fim");

        jLabel15.setText("Saldo Total");

        txSaldoTotal.setEditable(false);
        txSaldoTotal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txSaldoTotalActionPerformed(evt);
            }
        });

        jbChecarSaldo.setText("Ver Saldo");
        jbChecarSaldo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbChecarSaldoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Consultar Saldo");

        GroupLayout jpSaldoLayout = new GroupLayout(jpSaldo);
        jpSaldo.setLayout(jpSaldoLayout);
        jpSaldoLayout.setHorizontalGroup(
            jpSaldoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpSaldoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpSaldoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jpSaldoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jpSaldoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(133, 133, 133))
                    .addGroup(jpSaldoLayout.createSequentialGroup()
                        .addGroup(jpSaldoLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txSaldoTotal, GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txDataInicial))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpSaldoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, jpSaldoLayout.createSequentialGroup()
                                .addComponent(txDataFim, GroupLayout.PREFERRED_SIZE, 158, GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(GroupLayout.Alignment.TRAILING, jpSaldoLayout.createSequentialGroup()
                                .addComponent(jbChecarSaldo)
                                .addGap(86, 86, 86))))
                    .addGroup(jpSaldoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpSaldoLayout.setVerticalGroup(
            jpSaldoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpSaldoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jpSaldoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSaldoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txDataInicial, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDataFim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jLabel15)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSaldoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txSaldoTotal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbChecarSaldo))
                .addContainerGap(524, Short.MAX_VALUE))
        );

        tab.addTab("", jpSaldo);

        tabMovimentos.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Data", "Tipo", "SKU", "Estoque Movido", "Saldo"
            }
        ));
        jScrollPane4.setViewportView(tabMovimentos);

        GroupLayout jpMovimentosLayout = new GroupLayout(jpMovimentos);
        jpMovimentos.setLayout(jpMovimentosLayout);
        jpMovimentosLayout.setHorizontalGroup(
            jpMovimentosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpMovimentosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMovimentosLayout.setVerticalGroup(
            jpMovimentosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpMovimentosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        tab.addTab("", jpMovimentos);

        jPanel2.setBorder(BorderFactory.createEtchedBorder());

        bntProduto.setText("Produto");
        bntProduto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                bntProdutoActionPerformed(evt);
            }
        });

        btnExit.setText("Registrar Saida");
        btnExit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnEntry.setText("Registrar Entrada");
        btnEntry.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnEntryActionPerformed(evt);
            }
        });

        btnSaldo.setText("Consultar Saldo");
        btnSaldo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        btnLista.setText("Listar Movimentos");
        btnLista.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(bntProduto, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaldo, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btnLista, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnEntry, GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntProduto, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(btnExit, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSaldo, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnLista, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(btnEntry, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(517, Short.MAX_VALUE)))
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(tab, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tab.getAccessibleContext().setAccessibleName("");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txSKUActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txSKUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSKUActionPerformed

    private void txPrecoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPrecoActionPerformed

    private void txQtdSaidaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txQtdSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txQtdSaidaActionPerformed

    private void txSaldoTotalActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txSaldoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSaldoTotalActionPerformed

    private void bntProdutoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bntProdutoActionPerformed
        tab.setSelectedIndex(0);
    }//GEN-LAST:event_bntProdutoActionPerformed

    private void btnExitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        tab.setSelectedIndex(2);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEntryActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnEntryActionPerformed
        tab.setSelectedIndex(1);
    }//GEN-LAST:event_btnEntryActionPerformed

    private void btnSaldoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        tab.setSelectedIndex(3);
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnListaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        tab.setSelectedIndex(4);
    }//GEN-LAST:event_btnListaActionPerformed

    private void jbSalvarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
           
    try {
        int sku = Integer.parseInt(txSKU.getText());
        String nome = txNome.getText();
        String cat = jcCategoria.getSelectedItem().toString();
        double preco = Double.parseDouble(txPreco.getText());

        Produto p = new Produto(sku, nome, cat, preco, 0);
        produtoService.adicionar(p);

        atualizarTabelaProdutos();

        txSKU.setText("");
        txNome.setText("");
        txPreco.setText("");
        jcCategoria.setSelectedIndex(0); // opcional: seta para primeira categoria
        txSKU.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Erro ao salvar produto: " + e.getMessage());
    }



    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbRegEntradaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbRegEntradaActionPerformed
        try {
            String dataStr = txDataEntrada.getText().trim();
            int sku = Integer.parseInt(txSkuEntrada.getText().trim());
            int qtd = Integer.parseInt(txQtdEntrada.getText().trim());
            double valor = Double.parseDouble(txValorEntrada.getText().trim());

            if (dataStr.isEmpty() || qtd <= 0 || valor <= 0) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos corretamente!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Produto p = produtoService.getProdutoBySku(sku);
            if (p == null) {
                JOptionPane.showMessageDialog(this, "SKU não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            p.setQuantidade(qtd);

            Date data = UtilsDateFormat.parseT(dataStr);
            // Cria entrada (a data agora pode ser LocalDate ou Date)
            Entrada entrada = new Entrada(data, sku, qtd, valor);
            entradaService.adicionar(entrada);

            atualizarTabelaProdutos();
            atualizarTabelaEntradas();
            atualizarTabelaMovimentos();

            JOptionPane.showMessageDialog(this, "Entrada registrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "SKU, quantidade e valor devem ser numéricos!", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro inesperado ao registrar entrada!", "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbRegEntradaActionPerformed

    private void jbRegSaidaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbRegSaidaActionPerformed
        try {
        // Apenas pega a data da SAÍDA
            String data = txDataSaida.getText().trim();
            int sku = Integer.parseInt(txSkuSaida.getText());
            int qtd = Integer.parseInt(txQtdSaida.getText());

            if (data.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Data de saída não pode estar vazia!");
                return;
            }

        // Valida produto
            Produto p = produtoService.getProdutoBySku(sku);
            if (p == null) {
                JOptionPane.showMessageDialog(this, "SKU não encontrado!");
                return;
           }

            if (p.getQuantidade() < qtd) {
                JOptionPane.showMessageDialog(this, "Estoque insuficiente!");
                return;
            }
            Date data1 = UtilsDateFormat.parseT(data);
        // Registrar saída
            Saida s = new Saida(data1, sku, qtd);
            saidaService.adicionar(s); // salva no CSV + atualiza estoque automaticamente

        // Atualizar tabelas
            atualizarTabelaProdutos();
            atualizarTabelaEntradas();
            atualizarTabelaSaidas();
            atualizarTabelaMovimentos();

            JOptionPane.showMessageDialog(this, "Saída registrada com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar saída!");
            e.printStackTrace();
        }



    }//GEN-LAST:event_jbRegSaidaActionPerformed

    private void jbChecarSaldoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbChecarSaldoActionPerformed
        try {
            // 1️⃣ Lê as datas dos campos JTextField
            String inicioStr = txDataInicial.getText().trim();
            String fimStr = txDataFim.getText().trim();

            if (inicioStr.isEmpty() || fimStr.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "As datas não podem estar vazias!",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2️⃣ Converte para LocalDate usando UtilsDateFormat
            LocalDate inicio = UtilsDateFormat.parse(inicioStr);
            LocalDate fim = UtilsDateFormat.parse(fimStr);

            // 3️⃣ Usa EstoqueService para calcular saldo
            EstoqueService estoqueService = new EstoqueService(entradaService, saidaService, produtoService);
            double saldo = estoqueService.calcularSaldo(inicio, fim);

            // 4️⃣ Exibe o saldo
            txSaldoTotal.setText(String.valueOf(saldo));

        } catch (IllegalArgumentException e) {
            txSaldoTotal.setText("ERRO");
            JOptionPane.showMessageDialog(this,
                    "Data inválida: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            txSaldoTotal.setText("ERRO");
            JOptionPane.showMessageDialog(this,
                    "Erro inesperado ao calcular saldo!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }


    }//GEN-LAST:event_jbChecarSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton bntProduto;
    private JButton btnEntry;
    private JButton btnExit;
    private JButton btnLista;
    private JButton btnSaldo;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JButton jbChecarSaldo;
    private JButton jbExcluir;
    private JButton jbNovo;
    private JButton jbRegEntrada;
    private JButton jbRegSaida;
    private JButton jbSalvar;
    private JComboBox<String> jcCategoria;
    private JScrollPane jcTabela;
    private JPanel jpEntrada;
    private JPanel jpMovimentos;
    private JPanel jpProduto;
    private JPanel jpSaida;
    private JPanel jpSaldo;
    private JTabbedPane tab;
    private JTable tabAdicao;
    private JTable tabMovimentos;
    private JTable tabProduto;
    private JTable tabRemocao;
    private JTextField txDataEntrada;
    private JTextField txDataFim;
    private JTextField txDataInicial;
    private JTextField txDataSaida;
    private JTextField txNome;
    private JTextField txPreco;
    private JTextField txQtdEntrada;
    private JTextField txQtdSaida;
    private JTextField txSKU;
    private JTextField txSaldoTotal;
    private JTextField txSkuEntrada;
    private JTextField txSkuSaida;
    private JTextField txValorEntrada;
    // End of variables declaration//GEN-END:variables
}
